name: Check formatting

on:
  push:
    branches: [ main, 3la-pldi-push-main ]
  pull_request:
    branches: [ main, 3la-pldi-push-main ]

jobs:
  check-formatting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
